name: Deploy Azure Function (TypeScript + Cosmos)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          publish-profile: ''
          scm-do-build-during-deployment: true

      - name: Set Azure App Settings (Cosmos DB secrets)
        run: |
          az functionapp config appsettings set \
            --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --settings COSMOS_DB_ENDPOINT="${{ secrets.COSMOS_DB_ENDPOINT }}" COSMOS_DB_KEY="${{ secrets.COSMOS_DB_KEY }}"
